name: Update JioTV Plus Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download playlist
        run: |
          curl -L \
            -A "plaYtv/7.1.3 (Linux;Android 13) ygx/824.1 ExoPlayerLib/824.0" \
            -o jiotvplus.m3u \
            "${{ secrets.PLAYLIST_URL }}"

      - name: Add EPG
        run: |
          sed -i '/^#EXTM3U/ {
            /x-tvg-url=/! s|$| x-tvg-url="https://avkb.short.gy/epg.xml.gz"|
          }' jiotvplus.m3u

      - name: Replace existing User-Agent
        run: |
          sed -i 's|^#EXTVLCOPT:http-user-agent=.*|#EXTVLCOPT:http-user-agent=plaYtv/7.1.3 (Linux;Android 13) ygx/824.1 ExoPlayerLib/824.0|g' jiotvplus.m3u

      - name: Add User-Agent if missing
        run: |
          awk '
          {
            print
            if ($0 ~ /^#EXTINF:/) {
              getline nextline
              if (nextline !~ /^#EXTVLCOPT:http-user-agent=/) {
                print "#EXTVLCOPT:http-user-agent=plaYtv/7.1.3 (Linux;Android 13) ygx/824.1 ExoPlayerLib/824.0"
              }
              print nextline
            }
          }' jiotvplus.m3u > tmp.m3u

          mv tmp.m3u jiotvplus.m3u

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add jiotvplus.m3u

          git diff --cached --quiet && exit 0

          git commit -m "Auto-update jiotvplus.m3u"
          git push
